version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: cloudnative_final
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DEBUG=True
      - DB_NAME=cloudnative_final
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_HOST=postgres
      - DB_PORT=5432
      - SECRET_KEY=django-insecure-dev-key-change-in-production
      - ALLOWED_HOSTS=localhost,127.0.0.1
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app  # 開發時可以即時看到代碼變更

volumes:
  postgres_data: