apiVersion: v1
kind: Service
metadata:
  name: django
  namespace: cloudnative-final
spec:
  selector:
    app: django
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
  type: LoadBalancer