# Generated by Django 5.2 on 2025-05-21 10:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
        ("reviews", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DishReview",
            fields=[
                ("review_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        help_text="請給 0~5 之間的整數評分",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="星等評分",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True, help_text="可留空", verbose_name="文字評價"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, help_text="評論建立時間"),
                ),
                (
                    "order_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dish_reviews",
                        to="orders.orderitem",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dish_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("rating__gte", 0), ("rating__lte", 5)),
                        name="dish_rating_between_0_and_5",
                    )
                ],
                "unique_together": {("user", "order_item")},
            },
        ),
    ]
