# Generated by Django 5.2 on 2025-05-03 13:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('dish_id', models.AutoField(primary_key=True, serialize=False)),
                ('name_zh', models.CharField(max_length=100, verbose_name='菜名（中文）')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='菜名（英文）')),
                ('description_zh', models.TextField(blank=True, verbose_name='菜品描述（中文）')),
                ('description_en', models.TextField(blank=True, verbose_name='菜品描述（英文）')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='菜品價格')),
                ('image_url', models.URLField(blank=True, max_length=255, verbose_name='圖片 URL')),
                ('is_available', models.BooleanField(default=True, verbose_name='是否上架中')),
            ],
            options={
                'ordering': ['dish_id'],
            },
        ),
    ]
